### ISSUE TITLE
filtering penman output

### ISSUE THREAD

**Issue by arademaker** [goodmami/mrs-to-penman#3]
https://github.com/goodmami/mrs-to-penman/blob/5939e421cd789a11338ad0aa045d9830e49c33be/mrs_to_penman.py#L119-L145

Does it make sense to move this code, somehow, to pydelphin? It seems that besides this block of code, most of the code here is just scripts to process redwoods and generate penman files... right?

**Comment by goodmami** [comment]
No, this code does not belong in PyDelphin. Mainly, this is a wrapper of PyDelphin used for preprocessing data for a few experiments we did, and is not meant to be a general-purpose utility. PyDelphin has since gotten improved support for converting to PENMAN. For facilitating work with redwoods see https://github.com/delph-in/delphin.redwoods, which isn't working, but see https://github.com/delph-in/delphin.redwoods/pull/1.
